### ISSUE TITLE
Lettre imports are incorrect

### ISSUE THREAD

**Issue by mayacopeland** [mellowagain/gitarena#15]
While compiling gitarena locally, the dependency `lettre` complains about these imports being incorrect.

I am building this on on WSL 2.0 running Debian 10.
```
error[E0432]: unresolved imports `lettre::Mailbox`, `lettre::Tokio02Connector`, `lettre::Tokio02Transport`
  --> src/mail.rs:18:34
   |
18 | use lettre::{AsyncSmtpTransport, Mailbox, Message, Tokio02Connector, Tokio02Transport};
   |                                  ^^^^^^^           ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^ no `Tokio02Transport` in the root
   |                                  |                 |
   |                                  |                 no `Tokio02Connector` in the root
   |                                  |                 help: a similar name exists in the module: `Tokio02Executor`
   |                                  no `Mailbox` in the root```

**Comment by mellowagain** [comment]
Can you check what version of `lettre` you have installed?

**Comment by mayacopeland** [comment]
It appears I'm running lettre 0.9.6.

**Comment by mayacopeland** [comment]
Hmm. Reinstalling stuff shows that it's trying to install two versions of lettre?
![image](https://user-images.githubusercontent.com/58884617/144721524-5f68890a-777f-448b-a77f-487e4a0c6372.png)
![image](https://user-images.githubusercontent.com/58884617/144721527-f2f1dd43-a4da-4d88-bfec-9b1fd94664ee.png)

**Comment by mellowagain** [comment]
Oh yea seems like `lettre_email` isn't updated with the newest `lettre` beta. Considering `lettre_email` is unused, I have gone ahead and removed it in 2a99c47. Could you try again and see if the issue has been resolved?

**Comment by mayacopeland** [comment]
Yup. That worked.
