### ISSUE TITLE
Unable to initialize config in database

### ISSUE THREAD

**Issue by Tashima42** [mellowagain/gitarena#30]
Hi, I'm trying to run gitarena on my computer with a Postgres instance running on Docker.    
```
docker run --name git-arena -p 5432:5432 -e POSTGRES_PASSWORD=password -d postgres
```
But I'm having this error: `Error: Unable to initialize config in database`

My `DATABASE_URL` variable is: `postgresql://postgres:password@127.0.0.1:5432/gitarena`

I am able to connect to this instance using psql, can you help me with it?

`rustc --version`: `rustc 1.57.0 (f1edd0429 2021-11-29)`
`cargo --version`: `cargo 1.57.0 (b2e52d7ca 2021-10-21)`
`OS`: `EndeavourOS Linux x86_64`
`Kernel`: `5.15.12-arch1-1`

**Comment by mellowagain** [comment]
Below `Unable to initialize config in database` do you have any lines that say something along the lines of `caused by`? If yes, could you also provide them.

As a workaround you can run the `schema.sql` file into the `gitarena` database table. Then the check should succeed, provided your database connection works.

**Comment by Tashima42** [comment]
Full error log:
```
tashima@tashima ~/projects/personal/gitarena (main)$ ./target/release/gitarena 
Error: Unable to initialize config in database

Caused by:
    0: Failed to create initial database setup
    1: error returned from database: cannot insert multiple commands into a prepared statement
```

After running the `schema.sql`:
```
tashima@tashima ~/projects/personal/gitarena (main)$ ./target/release/gitarena 
thread 'main' panicked at 'explicit panic', src/licenses.rs:24:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
```

**Comment by mellowagain** [comment]
Thank you very much for the full error log. I'll fix it as soon as I have finished working on #29.

Regarding the second issue, the panic after starting: Did you clone the repository with submodules? If not, please download them with `git submodule update --init`. Make sure that the `license-list-data` submodule is in the same directory as the one you are starting gitarena from (in your case: `~/projects/personal/gitarena`).

**Comment by Tashima42** [comment]
Thanks! I managed to run the web server, I'm still having some errors in the login page, I'll report them later, but it's ok.

This is an awesome project, thank you for making it open source.

**Comment by mellowagain** [comment]
Thank you for your kind words. I have fixed the initial issue. Please open new issues for the other errors you are encountering.
