### ISSUE TITLE
Commits view loads the same commits over and over

### ISSUE THREAD

**Issue by Tashima42** [mellowagain/gitarena#33]
In the commits view, if you keep scrolling, the commits keep showing up. 

I have a repository with 41 commits, I think there's a limit of 20 commits per page, but if I keep scrolling, it just keeps loading the same commits over and over, when it should load just 3 pages (2 of 20 commits and 1 page with 1 commit).
<details>
  <summary>screenshot</summary>
      <img src="https://user-images.githubusercontent.com/23709916/149425290-a084be44-e4f5-47bc-ae47-a01fa51a2434.png" />
</details>

**Comment by mellowagain** [comment]
Thank you for your issue. I'm aware of it and have already opened a issue tracking this bug in #32. I'll close this as a duplicate. If you have any more information, feel free to comment on that issue. Thank you!
