### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by mzch** [mellowagain/gitarena#63]
I built GitArena from source code and tried to run it, but GitArena says, "Page Not Found".
Could you tell me how to fix this issue?

OS: macOS `13.3.1`
Browser: Chrome `112.0.5615.49`
Server: Debian `11.6`
Rust: `1.68.2 (6feb7c9cf 2023-03-26)`

<img width="1548" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/233233159-d0081339-3ddf-48da-b40e-335c8e34842f.png">

**Comment by mzch** [comment]
When selecting menu except `explore` menu, GitAreba show `Page Not Found`.

**Comment by mellowagain** [comment]
hi, yea this is intended. i never made a landing page so it'll result in a 404. i suggest the following workflow (as long as you configured the settings in the `settings` table in your gitarena database):

1. register an account by going to `/register` (or if you already did, log into it at `/login`)
2. verify your email address with the link u got sent to ur email
3. create a repository by going to `/new`, you can also try to import one from there (although that doesn't work correctly afaik)
4. once you did that, you can clone and push stuff with the url `/{username}/{repository}.git`
5. you can look at the repository at `/{username}/{repository}` (notice no `.git`)

**Comment by mzch** [comment]
Oh..OK. Thanks! And I have another questioin. When booting up GitArena, the following messages are shown:
```
Apr 21 13:53:15 ca gitarena[2041359]: #033[2m2023-04-21T04:53:15.293914Z#033[0m #033[31mERROR#033[0m ThreadId(01) #033[2mgitarena::ipc#033[0m#033[2m:#033[0m Failed to connect to workhorse: No such file or directory (os error 2)
Apr 21 13:53:15 ca gitarena[2041359]: #033[2m2023-04-21T04:53:15.293935Z#033[0m #033[33m WARN#033[0m ThreadId(01) #033[2mgitarena::ipc#033[0m#033[2m:#033[0m Workhorse features such as repo importing will be unavailable until IPC connection is established
```
Actually `/run/gitarena/workhorse` socket file is not created (`/run/gitareana` directory is existed), is this also OK?

**Comment by mellowagain** [comment]
yea you'd have to run `gitarena-workhorse` to create the socket. but if u dont need importing theres no reason to do so. that warning can be safely ignored.

**Comment by mzch** [comment]
Oh, thanks @mellowagain !
